# Generated by Django 3.2.8 on 2022-01-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ismade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='issent',
            field=models.BooleanField(default=False),
        ),
    ]
