# Generated by Django 3.2.8 on 2022-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_auto_20220103_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='infoFactory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
