# Generated by Django 3.2.8 on 2022-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_alter_packagefromclient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factory_info',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='codeFactory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
