# Generated by Django 3.2.8 on 2022-01-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_auto_20220112_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='factory_info',
            field=models.CharField(default='00', max_length=20),
        ),
    ]
