# Generated by Django 3.2.8 on 2022-01-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_alter_order_factory_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attention',
            field=models.BooleanField(default=False),
        ),
    ]
