# Generated by Django 3.2.8 on 2022-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0009_order_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='codeFactory',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='infoFactory',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
