# Generated by Django 3.2.8 on 2022-01-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0010_auto_20220112_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='outOfCollection',
            field=models.BooleanField(default=False),
        ),
    ]
