# Generated by Django 3.2.8 on 2022-01-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0011_furniture_outofcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderB2C',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='label.order')),
                ('nameOfClient', models.CharField(max_length=100)),
                ('surnameOfClient', models.CharField(max_length=100)),
            ],
            bases=('label.order',),
        ),
    ]
