# Generated by Django 3.2.8 on 2022-04-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0012_orderb2c'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clientApproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='factoryApproval',
            field=models.BooleanField(default=False),
        ),
    ]
