# Generated by Django 3.2.8 on 2022-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0013_auto_20220427_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='factory_info',
            field=models.CharField(max_length=20),
        ),
    ]
