# Generated by Django 3.2.8 on 2022-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0014_alter_order_factory_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('requirements', models.BooleanField(default=False)),
                ('typeOfLabel', models.CharField(choices=[('10x20', 'Standard'), ('A4', 'Bigstandard')], default='10x20', max_length=5)),
            ],
        ),
    ]
