# Generated by Django 3.2.8 on 2022-05-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0015_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label.factory'),
        ),
    ]
