# Generated by Django 3.2.8 on 2022-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0016_order_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
