# Generated by Django 3.2.8 on 2022-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0017_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='label',
            field=models.FileField(null=True, upload_to='Label_file'),
        ),
    ]
