# Generated by Django 3.2.8 on 2022-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0018_alter_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='typeOfLabel',
            field=models.CharField(choices=[('10x20', 'Standard'), ('A4', 'Big Standard')], max_length=300),
        ),
        migrations.AlterField(
            model_name='package',
            name='codeFactory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='infoFactory',
            field=models.CharField(max_length=50),
        ),
    ]
