# Generated by Django 3.2.8 on 2022-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0019_auto_20220521_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='labelCodeRequirement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factory',
            name='labelInfoRequirement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factory',
            name='orderRequirement',
            field=models.BooleanField(default=False),
        ),
    ]
