# Generated by Django 3.2.8 on 2022-05-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0020_auto_20220521_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='requirements',
        ),
    ]
