# Generated by Django 3.2.8 on 2022-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0022_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderb2c',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='numberOfStreet',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='numberofFlat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderb2c',
            name='nameOfClient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderb2c',
            name='surnameOfClient',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
