# Generated by Django 3.2.8 on 2022-05-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0023_auto_20220521_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.client'),
        ),
    ]
