# Generated by Django 3.2.8 on 2022-05-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0026_remove_packagefromclient_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label.client'),
        ),
    ]
