# Generated by Django 3.2.8 on 2022-05-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0027_campaign_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='transporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label.transporter'),
        ),
    ]
