# Generated by Django 3.2.8 on 2022-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0031_client_descriptiontofind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='factory_info',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
