# Generated by Django 3.2.8 on 2022-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0033_alter_order_factory_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='label',
            field=models.FileField(blank=True, null=True, upload_to='Label_file'),
        ),
    ]
