# Generated by Django 3.2.8 on 2022-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0034_alter_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderb2c',
            name='dropshippingApproval',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
