# Generated by Django 3.2.8 on 2022-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0035_alter_orderb2c_dropshippingapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderb2c',
            name='numberOfStreet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderb2c',
            name='numberofFlat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
