# Generated by Django 3.2.8 on 2022-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0037_rename_factory_info_order_factory_order_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderb2c',
            name='correctnessOfData',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
