# Generated by Django 3.2.8 on 2022-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0038_orderb2c_correctnessofdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderb2c',
            name='pickUpDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='productionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
