# Generated by Django 3.2.8 on 2022-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0040_alter_client_transporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderb2c',
            old_name='pickUpDate',
            new_name='pickupDate',
        ),
        migrations.AddField(
            model_name='orderb2c',
            name='dropshipingPartner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
