# Generated by Django 3.2.8 on 2022-06-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0041_auto_20220613_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='label.client'),
        ),
        migrations.AlterField(
            model_name='orderb2c',
            name='correctnessOfData',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderb2c',
            name='dropshippingApproval',
            field=models.BooleanField(default=False),
        ),
    ]
