
CWR=["IN&OUT DESIGN", "GALAXUS", "DECOVRY", "ART-STYLE", "L&F", "SETTIMO", "STK: BONAMI", "BONAMI","Mezoni", "LOVIN WORLD",
    "DESIGN_AG", "VIVRE_RO", "MYSTORE", "VEMZU", "PIGU", "MUZZA", "10DX", "NAPRIJED", "AIO_LIVING", "CRISTINA POPESCU","SPECIAL EVENTS","LIMANGO",
    "MEZONI","INTELLIGENT DESIGN", "SP_FR", "OPEN_DECO_HOME", "VSTYLE", "ART_STORE"]